### ISSUE TITLE
symbolUtils.renderPreviewHTML with CIMSymbol - CLI 4.15 & 4.14

### ISSUE THREAD

**Issue by anonanonttl** [Esri/arcgis-js-cli#76]
## Description
Hello there

I'm trying to show CIMSymbol with symbolUtils.renderPreviewHTML method with simple app generated with arcgis CLI 4.15 and I've got this error.

`Uncaught (in promise) TypeError: Cannot read property 'signal' of undefined
    at e.<anonymous> (CIMSymbolRasterizer.js:25)
    at i (generatorHelper.js:25)
    at Object.next (generatorHelper.js:25)
    at awaiterHelper.js:25
    at new Promise (<anonymous>)
    at Object.p [as create] (promiseUtils.js:25)
    at awaiterHelper.js:25
    at e.fetchPictureMarkerResource (CIMSymbolRasterizer.js:25)
    at e.<anonymous> (CIMSymbolRasterizer.js:25)
    at i (generatorHelper.js:25)`

I setted 'esri-native-promise' to false and the error desappeared but doens't work either.

```
featureLayer.when(() => {
   view.goTo(featureLayer.fullExtent);
     const graphicWithSimpleMarkerSymbo = new Graphic({
     symbol: {
       type: "simple-marker",
       color: "blue",
       outline: { color: [173, 44, 44, 1], width: 3 },
       size: 13,
     },
  });

  const grahicWithCimSymbol = new Graphic({
    symbol: {
      type: "cim",
      data: getPointSymbolData(),
    },
  });

  try {
    const renderEltSimple = document.getElementById("viewRenderWithSimpleMarkerSymbol");
    symbolUtils.renderPreviewHTML(graphicWithSimpleMarkerSymbo.symbol).then(elt => {
      renderEltSimple!.appendChild(elt);
    });

    const renderEltCim = document.getElementById("viewRenderWithCIMSymbol");
    symbolUtils.renderPreviewHTML(grahicWithCimSymbol.symbol).then(elt => {
      renderEltCim!.appendChild(elt);
    });
  } catch (e) {
    console.log(e);
  }
});
```

![Capture](https://user-images.githubusercontent.com/29690420/82078544-8fa53b80-96e1-11ea-91dd-f91ae08700c8.PNG)

With simple JS app, it's work :  https://codepen.io/anon-ttl/pen/abvaeXN

Thanks !!

**Comment by odoe** [comment]
There are a couple of things here.

You'll want to import symbolUtils like this.

```ts
import * as symbolUtils from 'esri/symbols/support/symbolUtils';
```

That's because I don't think it has a default export.

The other, which is default of the cli template is a change to the way the plugin is used

```js
// default config
new ArcGISPlugin({
  features: {
    '3d': false,
    has: {
      'esri-native-promise': true,
    },
  },
}),

// updated config
new ArcGISPlugin(),
```

There must be some underlying modules in the `symbolUtils` tree that is shared across some 3d modules. This is added to the plugin just so you can minimize the size of the deploy, which isn't very much, but it as saves a few seconds for the webpack compile depending on your machine.

Make those two changes and everything should start working again.

Thanks!

**Comment by anonanonttl** [comment]
Hi,

Yes

`'3d': true` resolved it.

Thanks
